const savollar = [
    `BLOKLI KODLASH NECH TURGA BO’LINADI, VA ULARNING NOMI NIMA?
JAVOB: 2 turga bo’linafi chiziqli va davriy`,
`DISKRETLASH NIMA?
JAVOB: signalni vaqt o’qi bo’yicha bo’laklash`,
`SIGNAL CHASTOTALARINI IFODALASH BIRLIGI NIMA?
JAVOB: gerts`,
`LOKAL BAZIS O’ZGARTIRISH ALGORITMI NIMA?
JAVOB: xaara`,
`INTEGRAL BAZIS O’ZGARTRISH ALGORITMI NIMA?
JAVOB: furye`,
`BAZIS FUNKSIYASI TASHKIL ETUVCHILARI 1 VA -1 GA EGA SPEKTRAL O’ZGARTRISH ALGORITMI QAYSI?
JAVOB: adamar o’zgartrish`,
`KO’P PROTSESSORLI TIZIMLARDA ISHLASH JARAYONI TASHKIL QILISH USULI NIMA?
JAVOB: ko’p protsessorli ishlov berish usuli`,
`RAQAMLI FILTRLARNING AFZALLIKLRI NIMA?
JAVOB: arzonlashtrilgan`,
`FURYE O’ZGARTRISHI NIMA UCHUN ISHLATILADI?
JAVOB: vaqt daminida davriy bo’lmagan signalni chastota daminiga aylantrish uchun`,
`DISKRET FURYE O’ZGARTRISHI BILAN FURYE O’ZGARTRISHI O’RTASIDAGI FARQ NIMA?
JAVOB: diskret furye uzluksiz signallar bilan ishlaydi
              Furye o’zgartrishi diskret signallar bilan ishlaydi`,
`VIDEOFAYLLARDAGI SIGNALLARNI TEBRANISHIGA ASOSAN NIMALAR SABAB BO’LADI?
JAVOB: kadrlarni yetishmovchiligi`,
`JPG FORMATINI YOYILMASI NIMA?
JAVOB: joint photographik expert group`,
`JPG TASVIRNI QANDAY STANDARTLARDA SIQADI?
JAVOB: DST VA DFT`,
`MATLAPDA BU UZATISH FUNKSIYASI XISOBLANIB NOMERATR VA MAXRAJNI PALINIMAL KOEFITSENLARI TO;PLAMINI VA VEKTORLARINI NOLGA O’ZGARTRADI BU QAYSI FUNKSIYA?
JAVOB: cheplfp`,
`DISKRET FILTRLAR QANDAY SHAKLGA EGA BO’LADI?
JAVOB: kanonik ko’chirilgan ketma-ket va elliptic`,
`VEYVLET FORMULASI?
JAVOB: F(a,b)=INTEGRAL –CHEKSIZDAN +CHEKSIZGACHA f(x)KSI`,
`SIQISH JARAYONIGA TO’G’RI TARIFNI BERING?
JAVOB: malumot va fayllarni xajmini kamaytrish`,
`MULTIPLEKSIYA NIMA?
JAVOB: kelayotgan ikkta signalni bitta kanal orqali birlashtrib uzatadi`,
`MALUMOTLARNI ASOSIY TURLARI?
JAVOB: matn, xaqiqiy, kompleks, mantiqiy element`,
`MALUMOTLARNI TAQDIM ETISHNING ASOSIY FORMATLARINI SANANG?
JAVOB: bayt, yarim so’z, so’z, ikkitalik so’z, kengaytrilgan so’z`,
`ADSP OILASIDA XAR BIR PROTSESSOR UCHUN NECHTA MUSTAQIL XISOBLASH BIRLIKLARI MAVJUD BO’LADI?
JAVOB: 3 ta`, 
`ADSP NECHA BITLI MALUMOTLARNI QAYTA ISHLASHGA MO’JALLANGAN?
JAVOB: 16 bitli`,
`ADSP 2, 21, 0, 10 PROTSESSORLARI QUYIDAGILARDAN QAYSI BIRI?
JAVOB: multiplayektori bori`,
`KO’PYADROLI SIGNAL PRATSESORLARIDA SPEKTRAL USULLARNI QAYTA ISHLASH ASOSAN NECHA XIL YECHIMLARNI TASHKIL ETADI?
JAVOB: 2 ta yadroga asoslangan va konveyrli `,
`SIGNALLARGA RAQAMLI ISHLOV BERISH JARAYONLARIDA TESKARI JARAYON NMANI ANGLATADI?
JAVOB: sinusoidal sintez`,
`BLOKLI KODLASH TURI NIMA?
JAVOB: 2 tur chiziqli va davriy`,
`NUTQ SIGNALLARI VA ELEKTROMIYAGRAFIYA SIGNALLARNING ASOSIY FARQI?
JAVOB: kirish chastotasida farq qiladi`,
`SHOVQINNI MINIMALLASHTRISH SIGNALNI QAYTA ISHLASH TEXNIKASINI QAYSI SOXASIDA QO’LLANILADI?
JAVOB: davr soxasida`,
`NUTQ SIGNALLARI TANIB OLISH JARAYONLARIDA SIGNALNI QAYSI KOYFITSENTLARIDAN KO’PROQ FOYDALANILADI?
JAVOB: MFT koyfitsentlari`,
`TASHQI MUHIT ALOQASIGA KO’RA TIZIMLAR QANDAY BO’LADI?
JAVOB: ochiq va yopiq`,
`TIZIMNI MURAKKABLIGI NIMAGA BOG’LIQ?
JAVOB: dinamik o’zgarish, ichki va tashqi aloqa`,
`KIX FILTRI UCHUN TO’G’RI TARIF BERILGAN QATORNI TOPING?
JAVOB: chekli impuls xarekteristkali filtr`,
`QUYIDAGI FILTRLASH FORMULASIDA KELTRILGAN Xn QANDAY SIGNAL?
JAVOB: filtrlanishi kerak bo’lgan signal`,
`LOPAS FILTR UCHUN TO’G’RI TARIF BERILGAN QATORNI TOPING?
JAVOB: bu turdagi filtr chastotasi aniqlanlan qiymatdan past bo’lgan signallarni o’tkazadi boshqa signallarni kesib tashlaydi`,
`XAYPAS FILTR UCHUN TO’G’RI TARIF BERILGAN QATORNI TOPING?
JAVOB: chastotasi aniqlangan qiymatdan baland bo’lgan signallarni o’tkazadi boshqa signallarni kesib tashlaydi`,
`BANDPAS FILTR UCHUN TO’G’RI TARIF BERILGAN QATORNI TOPING?
JAVOB: signal chastotasi berilgan o’tkazish chastotasi kengligi ichida bo;lgan qismini o’tkazadi`,
`QAYTA ISHLANADIGAN SIGNALLAR QANDAY GURUHLARGA BO’LINADI?
JAVOB: diskret, raqamli, analog`,
`TO’G’RI TARIF KELTRING – SVYORTKA JARAYONI BU?
JAVOB: bu funksional tahlil bo’lin 2 ta signalming ko’paytmasidan 3 o’zaro bog’lovchi signalning xosil bo’lish jarayoni`,
`KORRELYATSIYA JARAYONINI NECH XIL SHAKLI BOR?
JAVOB: 2 xil o’zaro korrelyatsiya va avto korrelyatsiya`,
`SVYORTKA AMALIDAN KO’P FOYDALANILADIGAN JARAYON QAYSI?
JAVOB: filtrlash jarayoni`,
`ANALOG SIGNAL QANDAY SIGNAL?
JAVOB: uzluksiz bo’ladi`,
`RAQAMLI SIGNAL QANDAY BO’LADI?
JAVOB: uzlukli bo’ladi`,
`SIGNALGA TO’G’RI TARIF BERILGAN QATORNI BELGILANG?
JAVOB: bu fizik jarayon bo’lib uning parametrlari uzatilayotgan xabarga muvofiq o’zgaradi`,
`ANALOG SIGNAL BILAN RAQAMLI SIGNAL O’RTASIDA QANDAY FARQ BOR?
JAVOB: analog signal- uzluksiz
              Raqamli signal –uzlukli`,
`QANDAY TURDAGI SIGNAL TASHQI TASIRLARDA KAMROQ O’ZGARADI?
JAVOB: raqamli signal`,
`SIGNALNI SEGMENTLASH JARAYONI QANDAY?
JAVOB: signalni malum bir bo’laklarga ajratish`,
       `O’ZARO KORRELYATSYA AMALI QANDAY BAJARILADI?
JAVOB: ikki signalni svyortkasi asosida bajariladi`,
`KOMPYUTER MARKAZIY BOSHQARUV VOSITALARIGA QAYSILAR KIRADI?
JAVOB: mikroprotsessor va mikrokontroller`,
`REAL VAQT TZIMLARI BU-?
JAVOB: boshqaruv paytida tashqi tasirlarga javob berishga ulguradigan tizimlar`,
`SIGNALNI DISKRETLASH NIMA?
JAVOB: signalni vaqt o’qi bo’yicha bo’laklash`,
`SIGNALNI KVANTLASH NIMA?
JAVOB: signalni amplitude o’qi bo’yicha bo’laklash`,
`SIGNALNI KODLASH NIMA?
JAVOB: signalni ikkilik sanoq sistemasiga o’tkazish`,
`RAQAMLI SIGNAL PROTSESSORLARI NIMA?
JAVOB: keladigan analog signalni raqamli qayta ishlashga yo’naltrilgan maxsus mikroprotsessorlar sinfi`,
`MATLAPDA clc BUYRUG’I NIMA VAZIFANI BAJARADI?
JAVOB: ishchi oynani tozalaydi`,
`MATLAP TZIMINING COMMAND WINDOV QISMIDA MALUMOTLARNI KIRITISH QAYSI BUYRUG’ BILAN BO’LADI?
JAVOB: <<`,
`MATLAP TIZIMIDA MASSIVLARNI KIRITISH QANDAY TARTIBDA KIRITILADI?
JAVOB: vergul bilan to’rtburchak qavs ichida`,
`SIGNALNI DASTLABKI XOLATI UNING QASI SOXASINI ANGLATADI?
JAVOB: amplitude, vaqt`,
`SIGNALNI VAQT SOXASIDA CHASTOTA SOXASIGA O’ZGARTRUVCHI ALGORITMLAR BERILGAN QATORNI BELGILANG?
JAVOB: veyvlet, furye, TST`,
`TIBBIYOTDA ISHLATILADIGAN SIGNAL TURLARI?
JAVOB: elektrokordialogiya 3 ta elektr degan javob`,
`SIGNAL PROTSESSORLARI ISHLAB CHIQARUVCHI MASHXUR FIRMALARNI KO’RSATING?
JAVOB: Texas Matorolla Analog devays`,
`SIGNALNI SVYORTKA QLISH NECHA XIL BO’LADI?
JAVOB: 2 xil Full svyortka, seing svryortka`,
`SIGNALNI KORRELYATSIYA QILISH NECHA XIL BO’LADI?
JAVOB: 2 xil`, 
`XISOBLASH MOSLAMALARI NECHA BITLI MALUMOTNI QAYTA ISHLAYDI?
JAVOB: 16 bitli`,
`RAQAMLI FILTRLAR NECHTA KATTA GURUXGA BO’LINADI?
JAVOB: 2 ta KIX va BIX`,
`DISKRETLASH NATIJASIDA QANDAY SIGNAL PAYDO BO’LADI?
JAVOB: diskret signal`,
`QANDAY JARAYON ASOSIDA DISKRET SIGNAL PAYDO BO’LADI?
JAVOB: diskret jarayon`,
`TASVIR SIGNALNING PIXSELLARI NECHA XIL RANGDAN TASHKIL TOPADI?
JAVOB: 3 xil qizil ko’k yashil`,
`MALUMOTLARNI SIQISH ALGORITMLARI NECHA GURUXGA BO’LINADI?
JAVOB: 2 guruxga yo’qotadigan va yo’qotmaydigan`,
`2 TA SIGNALNI O’XSHASHLIGI YOKI UMUMIY XUSUSIYATLARINI KO’RSATKICHI?
JAVOB: o’zaro korrelyatsiya`,
`RAQAMLI FILTR UCHUN TO’G’RI JAVOBNI ANIQLANG?
JAVOB: raqamli filtr raqamli ishlov berish usuli malum chegarada ajratuv jarayoni ketma-ketligi`,
`RAQAMLI FILTRNING AFZALLIGI NIMADA?
JAVOB: HAMMA JAVOB TO’G’RI`,
`DISKRET XOLDA SVYORTKANING 2 TURI MAVJUD VA ULAR NOMI?
JAVOB: chiziqli va siklik`,
`AFTOKORRELYATSIYA NIMA?
JAVOB: faqat bitta signalni mavjudligini nazarda tutadi va vaqt o’tishi bilan signalni tuzish yoki uning xarakati xaqida malumot beradi`,
`CHEKLI IMPULS XARAKTERISTKALI FILTRNI FARQINI AYTING?
JAVOB: impuls xarakteristkasi yoki impuls tavsifnomasi vaqt bo’yicha cheklangan bo’ladi`,
`IMPULS XARAKTERISTKANI AFZALLIGI NIMADA?
JAVOB: HAMMA JAVOB TO’G’RI`,
`CHEKSIZ IMPULS XARAKTERISTKALI FILTRNI TO’G’RI TARIFINI AYTING?
JAVOB: impuls vaqt mobaynida cheksiz bo’ladi`,
`REAL VAQT TIZIMLARI UCHUN TO’G’RI JAVOBNI AYTING?
JAVOB: boshqaruv paytida tashqi tasirlarga javob beradi`,
`SIGNAL PROTSESSORI ISHLAB CHIQARADIGAN DUNYODA YETAKCHI KOMPANIYA?
JAVOB: Mikrosistem SAN, IBM, Mikrosoft, Analog devays`,
`AVR mikrokontrolleri qaysi firmaga tegishli?
JAVOB: ATMEL`,
`QUINICS OPERATSION TIZIMI QACHON ISHLAB CHIQARILGAN?
JAVOB: 1982-yilda`,
`SIGNALLARNI QAYTA ISHLASH UCHUN ANANAVIY BOSQICHI?
JAVOB: signalni olish, dastlabki ishlov berish, belgilarni ajratish`,
`QUINICS OPERATSION TIZIMIGA TO’G’RI TARIF BERILGAN QATORNI TOPING?
JAVOB: real vaqt tizimli mikroyadroli operatsion tizim xisoblanadi`,
`KORRELYATSIYANI 2 SHAKLI MAVJUD ULARNING NOMI QANDAY?
JAVOB: avto va o’zaro korrelyatsiya`,
`RAQAMLI FILTRLAR IMPULS JAVOB REAKSIYASIGA KO’RA 2 TA KATTA TURGA BO’LINADI ULAR QAYSILAR?
JAVOB: cheksiz va chekli`,
`DISKRETLASH CHASTOTASI QAYSI TEOREMA ASOSIDA OLINGAN?
JAVOB: Katelnikov`,
`RAQAMLI SXEMALAR BILAN TAQQOSLAGANDA ANALOG SXEMALAR NIMAGA NISBATAN SEZGIRROQ?
JAVOB: qarish`,
`FURYE TAHLILI NIMA QILADI?
JAVOB: furye tahlili signalni asl damendan chastota dameniga o’tkazadi`,
`TABIATDA SIGNALLARNI ASOSAN KO’RINISHI QANDAY BO’LADI?
JAVOB: analog ko’rinishda`,
`DFT QIYMATLARI QANDAY OLINADI?
JAVOB: turli chastotalar tarkibi qismlarga ajratish orqali`,
`ELEKTR SIGNAL DEB NIMAGA AYTILADI?
JAVOB: elektron jarayon bo’lib….`,
`KVANTLASH JARAYONIDA ……. KERAK?
JAVOB: signallarni butun diapason darajalarga bo’linib ularning soni berilgan bit kengligi sonlari bilan ifodalanadi`,
`XABAR MANBADAN ISTEMOLCHIGA YETKAZIB BERISH UCHUN FOYDALANILADIGAN TEXNIKA QURILMALARI TO’PLAMI BU?
JAVOB: aloqa tizimi`,
`MATEMATIK NUQTAI NAZARDAN UZLUKSIZ SIGNAL DOIMIY NIMADA IFODALANADI?
JAVOB: funksiya yordamida`,
`TELEFON SIGNALI SPEKTOR KENGLIGI QANCHA?
JAVOB: 300 – 3400`,
`RADIOESHITRISH SIGNAL SPEKTOR KENGLIGI QANCHA?
JAVOB: 300 – 3400`,
`TELEGRAF SIGNAL SPEKTOR KENGLIGI QANCHA?
JAVOB: max 100 gertsgacha`,
`TELVIZION SIGNAL VIDEOSIGNAL SPEKTORI KENGLIGI QANCHA?
JAVOB: 6 000 500 gerts`,
`DUNYODAGI ENG MUKAMMAL VIDEOUZATISH TIZIMI QAYSI?
JAVOB: insonning ko’rish tizimi`,
`MATLAP PAKETIDA SIGNALNI EKRANGA CHOP ETISH, TASVIRLASH UCHUN QAYSI FUNKSIYADAN FOYDALANILADI?
JAVOB: plot`,
`PHITON DASTURLASH TILIDA MATRISSA BILAN ISHLASH KUTUBXONASI?
JAVOB: nanpay`,
`DISKRETLASH CHASTOTASI 11 Kgerts SIGNALNI VAQT O’QI BO’YICHA NECHTA BLOKKA DISKRETLANADI?
JAVOB: 11050`,
`SIGNALNI KVANTLASH QAYSI O’Q BO’YICHA AMALGA OSHIRILADI?
JAVOB: amplitude`,
 `SIGNALNI DISKRETLASH QAYSI O’Q BO’YICHA AMALGA OSHIRILADI?
JAVOB: vaqt`,
`NUTQ SIGNALI SOHASIDAGI BOSHLANG’ICH VA TUGALLANISH KOEFITSENTLARI ORASIDAGI FARQNI ANIQLASH NUTQ SIGNALINI QAYSI PARAMETRLARINI IFODALAYDI?
JAVOB: qiymatlar sonini bildiradi`,
`SIGNALNI TEZKOR FURYE O’ZGARTRISHI AMALGA OSHIRILGANDA UNING NATIJAVIY QIYMATLARI QAYSI SOHADA IFODALANADI?
JAVOB: amplituda va chastota`,
`DASTLAB ANALOG SIGNALLAR QANDAY FILTRLAR YORDAMIDA FILTRLANADI?
JAVOB: analog filtr`,
`SIGNALNI ANALOG FILTR BILAN FILTRLAGANDA QANDAY SIGNAL HOSIL BO’LADI?
JAVOB: analog signal`,
`QANDAY FILTRLARNI ISHLATISH YORDAMIDA RAQAMLI SIGNALLARNI FILTRLASH MUMKIN?
JAVOB: raqamli`,
`SIGNALLARNI BO’LAKLARGA TAQSIMLASH QANDAY JARAYON?
JAVOB: segmentlash`,
`TURLI TURGADI SIGNALLARNI TURLI SHOVQINLARDAN XALAQITLARDAN TOZALASH JARAYONI BU-?
JAVOB: filtrlash`,
`SIGNALNI BIR BIRIGA MOSLIGINI TEKSHIRISH JARAYONI BU-?
JAVOB: korrelyatsiya`,
`MATLAP PAKETIDA MALUMOTLAR ….. SHAKLIDA IFODALANADI?
JAVOB: matrissa`,
`MATLAP PAKETIDA workspage QISMIDA NIMALAR SAQLANADI?
JAVOB: natija, o’zgaruvchini qiymatlari`,
`MATLAP PAKETIDA Command History QISMIDA NIMA SAQLANADI?
JAVOB: buyruqlar tarixi`,
`1 kGerts CHASTOTA NECHA GERTS CHASTOTA BO’LADI?
JAVOB: 1000 gerts`,
`Close all QANDAY AMAL?
JAVOB: barcha figurani yopadi, BARCHA JAVOB NOTO’G’RI`,
`MIYYADAN OLINADIGAN SIGNALLAR?
JAVOB: elektroensofolografiya`,
`MUSHAKLARDAN OLINADIGAN BIOSIGNALLAR QANDAY SIGNALLAR TURIGA MANSUB?
JAVOB: elektromyografiya`,
`TABIATDA UCHRAYDIGAN SIGNALLAR ASOSIY QANDAY TURLARGA BO’LINADI?
JAVOB: vaqt bo’yicha o’zgaradigan va o’zgarmaydigan`,
`SIGNALLAR BULL ALGEBRASIDA QANDAY IFODALANADI?
JAVOB: 0 va 1 bilan`,
`SIGNALLARGA RAQAMLI ISHLOV BERISHDA QAYSI BIRI NASOSDA SVYORTKA ALGORITMI YOTADI?
JAVOB: filtr`,
`AVR MIKROKONTROLLERI QANDAY ARXITEKTURADA TUZILGAN?
JAVOB: resk`,
`MATLAPDA FFTX BUYRUG’I NIMA VAZIFANI BAJARADI?
JAVOB: tezkor furye o’zgartrishi`,
`KORRELYATSIYA JARAYONI NECHA XIL SHAKLI BOR?
JAVOB: 2 xil`,
`MATLAPDA pwlch BUYRUG’I NIMA VAZIFANI BAJARADI?
JAVOB: signalni spektral qvorishni isbotlagan`,
`AUDIO FORMATLARINING TURLARI?
JAVOB: aac, var va.h.k`,
`MATLAP PAKETIDA TASVIRLARNI O’QIB OLISH?
JAVOB: imread`,
`MATLAP PAKETIDA TASVIRLARNI EKRANGA CHIQARISH?
JAVOB: imshow`,
`MATLAP PAKETIDA TASVIRNI GISTOGRAMMASINI CHIQARISH?
JAVOB: imhis`,
`AUDIO SIGNALLARNI 2 TA FORMATI BOR ULAR QAYSILAR?
JAVOB: mono va sterio`,
`AUDIO SIGNALLARNI O’QIB OLISH BUYRUQLARI?
JAVOB: audioread, veyvread`,
`GISTOGRAMMANI NORMALLASHTRISH BUYRUG’I TASVIRLARDA?
JAVOB: histech`,
`INSON QULOG’I ESHITAOLADIGAN TOVUSH CHASTOTALARI?
JAVOB: 20 – 20 000`,
`ANALOG SIGNALLAR ….. ?
JAVOB: vaqt o’tishi bilan doimiy ravishda o’zgarib turadi?`,
`NEGA ANALOGGA QARAGANDA RAQAMLI SIGNALLARNI QAYTA ISHLASH TIZIMI HUSUSIYATLARINI YAXSHILASH OSONROQ?
JAVOB: raqamli 0 dan 9 gacha analog tok dyot`,
`RAQAMLI SIGNALLARNI QANDAY QLIB QAYTA ISHLANADI?
JAVOB: dastur yordamida`,
`ODDIY DSP TIZMIDA NIMALAR MAVJUD?
JAVOB: analog raqamli o’zgartrgich, port, raqamli analog o’zgartrgich, xotira, spyu`,
`KO’P PROTSESSORLI TIZIMLARDA XISOBLASH JARAYONI QANDAY USULDA TASHKIL QILINADI?
JAVOB: ko’p protsessorli ishlov berish usuli`,
`SIGNALLARNI ADAPTI FILTRLASHDA FILTR KOEFITSENTLARI QANDAY XOSIL QILINADI?
JAVOB: kelayotgan signalni shovqin bilan signalni koefitsentlardan yeg’ib filtr xosil qiladi`,
`PHYTON DASTURLASH TILIDA GRAFIK INTERFEYSI BILAN ISHLOVCHI KUTUBXONA?
JAVOB: skintr`
]






const inp = document.querySelector(".inp")
const ul = document.querySelector(".ul")
const choise = document.querySelector(".choise")


function search1(){
    
    if(choise.value==1){
        savol = savollar
    }

    if(inp.value<2) return
    let newLst = []
    for(let sav of savol){
        if(sav.toLocaleLowerCase().includes(inp.value.toLocaleLowerCase())){
            newLst.push(sav)
        }
    }
    
    render(newLst)
}


function render(lst){
    ul.innerHTML = null

    if(lst.length==0) sav=savollar
    
    for(let sav of lst){
        let li = document.createElement("li")
        li.textContent = sav
        ul.append(li)
    }
}


inp.addEventListener("keyup",()=>{

    search1()
})


render(savollar)

